- name : Configure Docker on EC2 Instances & deploy the app in prod-server
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service docker
    command : sudo systemctl start

  - name: Deploy Docker Container to prod-server
    command: docker run -itd -p 8084:8081 abhishekgowda123/banking-project:1.0
