- name : Configure Docker on test-server Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating yum
    command : sudo yum update

  - name : Install Docker
    command : sudo yum install  docker -y

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name : run the Bank application
    command: docker run -itd -p 8084:8081 abhishekgowda123/banking-project:1.0
